{
 "title": "Power",
 "time": { "from": "now-24h", "to": "now" },
 "panels": [
  {
   "title": "Energy usage",
   "type": "stat",
   "gridPos": { "h": 5, "w": 8, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "watth" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "difference = () => {\n  pierwszy = from(bucket: \"temp\")\n  |> range(start: v.timeRangeStart, stop:v.timeRangeStop)\n  |> filter(fn: (r) =>r._measurement == \"power\" and r._field == \"total\" )\n  |> first()\n  |> truncateTimeColumn(unit: 1h)\n  |> pivot(rowKey: [\"_time\"], columnKey: [\"phase\"], valueColumn: \"_value\")\n  |> map(fn: (r) => ({ r with TOTAL: r.RED + r.YELLOW + r.BLUE }))\n  |> keep(columns: [\"TOTAL\",\"_measurement\"])\n  \n\n  ostatni = from(bucket: \"temp\")\n  |> range(start: v.timeRangeStart, stop:v.timeRangeStop)\n  |> filter(fn: (r) =>r._measurement == \"power\" and r._field == \"total\" )\n  |> last()\n  |> truncateTimeColumn(unit: 1h)\n  |> pivot(rowKey: [\"_time\"], columnKey: [\"phase\"], valueColumn: \"_value\")\n  |> map(fn: (r) => ({ r with TOTAL: r.RED + r.YELLOW + r.BLUE }))\n  |> keep(columns: [\"TOTAL\",\"_measurement\"])\n  \n  joined = join(tables:{pierwszy:pierwszy, ostatni:ostatni}, on:[\"_measurement\",])\n  //|> yield(name: \"JOINED\")\n  |> map(fn: (r) => ({ r with TOTAL: r.TOTAL_ostatni - r.TOTAL_pierwszy,}))\n  |> keep(columns: [\"TOTAL\"])\n  |> yield(name: \"WYNIK\")\n  return joined\n\n  }\n\ndifference()"
    }
   ]
  },
  {
   "title": "Energy usage per phase",
   "type": "stat",
   "gridPos": { "h": 5, "w": 9, "x": 8, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "watth" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "difference = () => {\n  pierwszy = from(bucket: \"temp\")\n  |> range(start: v.timeRangeStart, stop:v.timeRangeStop)\n  |> filter(fn: (r) =>r._measurement == \"power\" and r._field == \"total\" )\n  |> first()\n  |> truncateTimeColumn(unit: 1h)\n  |> pivot(rowKey: [\"_time\"], columnKey: [\"phase\"], valueColumn: \"_value\")\n\n  ostatni = from(bucket: \"temp\")\n  |> range(start: v.timeRangeStart, stop:v.timeRangeStop)\n  |> filter(fn: (r) =>r._measurement == \"power\" and r._field == \"total\" )\n  |> last()\n  |> truncateTimeColumn(unit: 1h)\n  |> pivot(rowKey: [\"_time\"], columnKey: [\"phase\"], valueColumn: \"_value\")\n  \n  joined = join(tables:{pierwszy:pierwszy, ostatni:ostatni}, on:[\"_field\",\"_start\",\"_stop\",\"_measurement\",])\n  //|> yield(name: \"JOINED\")\n  |> map(fn: (r) => ({ r with RED: r.RED_ostatni - r.RED_pierwszy, \n                        YELLOW: r.YELLOW_ostatni - r.YELLOW_pierwszy,\n                        BLUE: r.BLUE_ostatni - r.BLUE_pierwszy,\n                        }))\n  |> keep(columns: [\"RED\",\"YELLOW\",\"BLUE\"])\n  |> yield(name: \"WYNIK\")\n  return joined\n\n  }\n\ndifference()"
    }
   ]
  },
  {
   "title": "Power factor",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 7, "x": 17, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "query": "from(bucket: \"temp\")\n  |> range(start: v.timeRangeStart, stop:v.timeRangeStop)\n  |> filter(fn: (r) =>\n    r._measurement == \"power\" and\n    r._field == \"pf\"\n  )\n   |> set(key: \"_field\", value: \"\")\n   |> aggregateWindow(every: v.windowPeriod, fn: mean)"
    }
   ]
  },
  {
   "title": "Voltage",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 13, "x": 0, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "volt" } },
   "targets": [
    {
     "query": "from(bucket: \"temp\")\n  |> range(start: v.timeRangeStart, stop:v.timeRangeStop)\n  |> filter(fn: (r) =>\n    r._measurement == \"power\" and\n    r._field == \"voltage\"\n  )\n   |> set(key: \"_field\", value: \"\")\n   |> aggregateWindow(every: v.windowPeriod, fn: mean)"
    }
   ]
  },
  {
   "title": "Power",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 11, "x": 13, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "targets": [
    {
     "query": "from(bucket: \"temp\")\n  |> range(start: v.timeRangeStart, stop:v.timeRangeStop)\n  |> filter(fn: (r) =>\n    r._measurement == \"power\" and\n    r._field == \"power\"\n  )\n   |> set(key: \"_field\", value: \"\")\n   |> aggregateWindow(every: v.windowPeriod, fn: mean)"
    }
   ]
  },
  {
   "title": "Current",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 13, "x": 0, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "amp" } },
   "targets": [
    {
     "query": "from(bucket: \"temp\")\n  |> range(start: v.timeRangeStart, stop:v.timeRangeStop)\n  |> filter(fn: (r) =>\n    r._measurement == \"power\" and\n    r._field == \"current\"\n  )\n   |> set(key: \"_field\", value: \"\")\n   |> aggregateWindow(every: v.windowPeriod, fn: mean)"
    }
   ]
  },
  {
   "title": "Total Power",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 11, "x": 13, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "targets": [
    {
     "query": " from(bucket: \"temp\")\n  |> range(start: v.timeRangeStart, stop:v.timeRangeStop)\n  |> filter(fn: (r) =>r._measurement == \"power\" and r._field == \"power\" )\n   |> set(key: \"_field\", value: \"\")\n   |> truncateTimeColumn(unit: 1s)\n   |> pivot(rowKey: [\"_time\"], columnKey: [\"phase\"], valueColumn: \"_value\")\n   |> map(fn: (r) => ({ r with _value: r.RED + r.YELLOW +r.BLUE }))\n  // |> set(key: \"_field\", value: \"\")\n   |> keep(columns: [\"_value\",\"_time\",])\n  // |> keep(columns: [\"_value\",\"_time\",\"_field\"])\n   |> aggregateWindow(every: v.windowPeriod, fn: mean)"
    }
   ]
  }
 ]
}